apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  ports:
  - port: 8080
    nodePort: 30000
  selector:
    app: jenkins
    tier: cicd
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  labels: 
    app: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
   matchLabels:
     app: jenkins
     tier: cicd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
        tier: cicd
    spec:
       containers:
       - image: demetrix/jenkins:v1
         name: jenkins
         ports:
         - containerPort: 8080
           name: jenkins
         volumeMounts:
         - name: jenkins-vol
           mountPath: /var/jenkins
       volumes:
       - name: jenkins-vol
         persistentVolumeClaim:
           claimName: jenkins-pv-claim
